# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcSesh < Formula
  desc "sesh fork with built-in Claude Code live status in the picker"
  homepage "https://github.com/Wingsdh/cc-sesh"
  version "2.0.0"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.0.0/cc-sesh_Darwin_x86_64.tar.gz"
      sha256 "5693cf49f04b8d4c2ff3e84633e4e215c2c6d77803550d9a5d9a8d5f8900d65d"

      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.0.0/cc-sesh_Darwin_arm64.tar.gz"
      sha256 "61753dc6bfe329faf60d6ea8af6519ff7e9072a6c9f04d79bf81a3a592a7e6a5"

      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.0.0/cc-sesh_Linux_x86_64.tar.gz"
      sha256 "badc2cf99924c758406650573058743c89d388706b2a4a70990069b799281186"
      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.0.0/cc-sesh_Linux_arm64.tar.gz"
      sha256 "9b1b1bd68679cb970ba0693924e2ffb4a946e3c6e86b6d1b1f26533c0edac469"
      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
  end
end
