# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcSesh < Formula
  desc "sesh fork with built-in Claude Code live status in the picker"
  homepage "https://github.com/Wingsdh/cc-sesh"
  version "2.1.1"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.1.1/cc-sesh_Darwin_x86_64.tar.gz"
      sha256 "a4e5f829d39ccd60bbdc2d2149780a4786b9687bedf442aff0a9f2976d13aabf"

      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.1.1/cc-sesh_Darwin_arm64.tar.gz"
      sha256 "126342c8c68959977575aab83bdf3d1c6b95bebc59dae33aed737672568faddd"

      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.1.1/cc-sesh_Linux_x86_64.tar.gz"
      sha256 "9306e6c874a19046bce8216615bda8b2c4dd0cea3f0d689b7a6cbd4c89274faa"
      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wingsdh/cc-sesh/releases/download/v2.1.1/cc-sesh_Linux_arm64.tar.gz"
      sha256 "cdbb99ad90b24d8e049b885a7e4d8a04db39e31146e47af08d502b0c0bb80ea0"
      define_method(:install) do
        bin.install "cc-sesh"
        man1.install "share/man/man1/cc-sesh.1"
      end
    end
  end
end
